spring:
  application:
    name: task-tracker-scheduler

  datasource:
    url: jdbc:postgresql://database:5432/task_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: broker:29092
    email-sending-tasks-topic: EMAIL_SENDING_TASKS
server:
  port: 8082