spring:
  application:
    name: task-tracker-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5434/task_tracker
    username: task_tracker_service
    password: qweasd123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    email-sending-tasks-topic: EMAIL_SENDING_TASKS

logging:
  level:
    root: INFO
  file:
    name: task-tracker-scheduler.log
    path: /
server:
  port: 8082